---
fixtures:
  forge_modules:
    stdlib: puppetlabs/stdlib
    apt: puppetlabs/apt
    archive: puppet/archive
    postgresql: puppetlabs/postgresql
    concat: puppetlabs/concat
    systemd: puppet/systemd
